### ISSUE TITLE
shortest job first

### ISSUE THREAD

**Issue by Kishorsarswat** [shreyanshanchlia/OS-Process-Scheduler#4]
The algorithm is not working as expected in the preemptive version. After the first preemption, it assumes that the process is completed, which leads to the wrong TAT, waiting time, and completion time in the table. Because of this it is producing -ve waiting time which is not possible at all.

**Comment by shreyanshanchlia** [comment]
@Kishorsarswat  try to run at 1x speed. If the issue still persists, reply back. If you change speed at runtime there might be some issues.

**Comment by shreyanshanchlia** [comment]
I'm able to reproduce this issue. 
Eg. When 
P1:
AT: 0
BT: 9
P2:
AT: 0
BT: 2
P3:
AT: 2
BT: 3
This is taking P1 as first process instead of P2.
