### ISSUE TITLE
run time problem

### ISSUE THREAD

**Issue by Daim58** [shreyanshanchlia/OS-Process-Scheduler#7]
![2](https://user-images.githubusercontent.com/64218421/80126321-90e6bb00-85b0-11ea-8f92-1f8f2c168c1f.JPG)
![1](https://user-images.githubusercontent.com/64218421/80126326-92b07e80-85b0-11ea-9aa1-1e8ce768a8ce.JPG)

**Comment by shreyanshanchlia** [comment]
I'm not able to reproduce this issue even with the same data. Can you brief me on how you encountered the issue and the version you are using?
